spring.application.name=Ericsson Datathon Project
spring.datasource.url=jdbc:h2:file:./data/datathon_user_db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=VQk6?Mw)7\5mWiAJJ_&7K'
spring.sql.init.platform=h2
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false